# Generated by Django 3.0.6 on 2020-05-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_name', models.CharField(max_length=250)),
                ('Date', models.CharField(max_length=250)),
                ('Image_type', models.CharField(max_length=250)),
                ('Input_image', models.CharField(max_length=1000)),
                ('Output_image', models.CharField(max_length=1000)),
            ],
        ),
    ]
