# Generated by Django 3.0.6 on 2020-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_name', models.ImageField(blank=True, null=True, upload_to='')),
                ('Date', models.CharField(max_length=250)),
                ('Image_type', models.CharField(max_length=250)),
                ('Input_image', models.CharField(max_length=1000)),
                ('Output_image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='images',
        ),
    ]
