# Generated by Django 3.0.6 on 2020-05-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20200521_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='image',
            name='Input_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
