# Generated by Django 3.0.6 on 2020-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20200528_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Input_image',
            field=models.URLField(),
        ),
    ]
