# Generated by Django 3.0.6 on 2020-06-25 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20200528_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Image_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='Image_type',
        ),
        migrations.AlterField(
            model_name='image',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
