# Generated by Django 3.0.8 on 2020-07-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20200625_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Gallery',
        ),
    ]
