# Generated by Django 3.0.8 on 2020-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20200827_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Input_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
