# Generated by Django 3.0.8 on 2020-08-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20200827_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_image', models.ImageField(upload_to='assets/images')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
