# Generated by Django 3.0.8 on 2020-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('i_image', models.ImageField(upload_to='assets/images')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
