# Generated by Django 3.0.3 on 2020-09-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook_url',
            field=models.URLField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='team',
            name='github_url',
            field=models.URLField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin_url',
            field=models.URLField(default='SOME STRING'),
        ),
    ]
